name: Format

on: [ push, pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-python
      
      - uses: ./.github/actions/install-just

      - name: Ensure formatting
        run: just format-check