name: Lint

on: [ push, pull_request ]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-python
      
      - uses: ./.github/actions/install-just

      - name: Run linter
        run: just lint