name: Test

on: [ pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/setup-python
      
      - uses: ./.github/actions/install-just

      - name: Run tests
        run: just test
