name: Run Unit Tests
on: [pull_request]

jobs:
  test-coinbase-agentkit-python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/omny_py
    strategy:
      matrix:
        python: ["3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run tests
        run: just test